// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvapuajektabkszgdpic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2YXB1YWpla3RhYmtzemdkcGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTEwNzcsImV4cCI6MjA2NDA4NzA3N30.RGMNY3_S4_LoOaMmG6yENQ--OknlLPR-hmFHpHmI2xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});